#include <iostream>
#include <fstream>
#include "lab04_tasks.hpp"

// name of the image that the tasks automatically pick. The image must be inside the docs folder in order for this to work properly
#define DEFAULT_IMAGE "street_scene.png"

using namespace std;

string findSeparator()
{
    #ifdef _WIN32
    return "\\";
    #elif _WIN64
    return "\\";
    #elif __APPLE__ || __MACH__
    return "/";
    #elif __linux__
    return "/";
    #elif __FreeBSD__
    return "/";
    #elif __unix || __unix__
    return "/";
    #else
    return "/";
    #endif
}  

string getImageInDefaultLocation(string execPath)
{
    // define correct separator based on current operating system
    string separator = findSeparator();
    // split path to find the correct folder

    // split path into all its components
    vector<string> path;
    int sepPos = execPath.find(separator,1), lastPos = 0;
    while (sepPos != string::npos)
    {
        path.push_back(execPath.substr(lastPos,sepPos-lastPos));
        lastPos = sepPos+1;
        sepPos = execPath.find(separator, lastPos);
    }

    if ((path.size() >= 3) && (path[path.size()-1] == "src") && (path[path.size()-2] == "build"))
    {
        // rebuild path to point to the default street_scene.png location
        // assumes the executable is generated by cmake inside the folders <PROJECT-MAIN-FOLDER>/build/src
        // and removes from the path the last two elements(/build/src) and place in their stead "/doc/DEFAULT_IMAGE"
        string filePath(path[0]);
        for (int i = 1; i < path.size()-2; i++)
        {
            filePath = string(filePath + separator + path[i]);
        }
        filePath = string(filePath + separator + "docs" + separator + DEFAULT_IMAGE);
        return filePath;
    }
    else
    {
        cout << "You must specify the image file or insert the full path when running thhis executable.\nThe default path does not exists" << endl;
        exit(1);
    }

    return "";
}

int main(int argc, char** argv)
{
    // Check whether the input arguments are the right amount
    if ((argc != 3) && (argc != 2))
    {
        throw invalid_argument("Usage: <path>/lab04 <task n°> <(OPTIONAL)image path>");
    }
    
    // Check if a file path is specified, otherwise tries to take the image in the default location
    FILE *file;
    string filename;
    if (argc == 3)
        filename = string(argv[2]);
    else
        filename = getImageInDefaultLocation(string(argv[0]));
    
    if (!(file = fopen(filename.c_str(), "r")))
        throw invalid_argument(filename + " not found"); 
    fclose(file);

    // Check whether the task n° is an integer, if it isn't than exception is thrown within the switch-case below
    int task = 0;
    if (isdigit(*argv[1]))
        task = stoi(argv[1]);
    
    switch (task)
    {
    case 1:
        task01(filename);
        break;

    case 2:
        task02(filename);
        break;

    case 3:
        task03(filename);
        break;

    case 4:
        task04(filename);
        break;
    
    default:
        throw invalid_argument("Task n° must be an integer between 1 and 4");
        break;
    }
}